spring.application.name=atairu-backend


spring.datasource.url=jdbc:postgresql://localhost:5432/atairu_db
spring.datasource.username=postgres
spring.datasource.password=postSenha123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.properties.hibernate.spatial.dialect=org.hibernate.spatial.dialect.postgis.PostgisDialect
